{% set version = "0.12.0rc0" %}

package:
  name: tensorflow
  version: {{ version }}

source:
  fn: tensorflow-{{ version }}.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/0.12.0-rc0.tar.gz
  #url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz

build:
  number: 0
  #  Google supplies whl files for:
  # - Linux: Python 2.7, 3.4 and 3.5
  # - OS X: Python 2.7, 3.4 and 3.5
  # - Win-64: Python 3.5
  skip: True  # [win32]
  skip: True  # [win64 and not py35]
  skip: True  # [py26]
  skip: True  # [py33]
  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

requirements:
  build:
    - python
    - pip
    - numpy >=1.11.0
    - protobuf ==3.0.0
    - six >=1.10.0
    - wheel >=0.26
    - cmake
    - swig
    - zlib
  run:
    - python
    - numpy >=1.11.0
    - protobuf ==3.0.0
    - six >=1.10.0

test:
  imports:
    # Skip the import test on Linux as wheel file require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    - tensorflow  # [not linux]

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow

extra:
  recipe-maintainers:
    - jjhelmus
    - danielfrg
    - waitingkuo
    - ghego
